export const AUTHENTICATING = 'AUTHENTICATING';
export const AUTHENTICATION_FAILURE = 'AUTHENTICATION_FAILURE';
export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS';
export const CLEAR_ERROR = 'CLEAR_ERROR';
export const FETCHED_EXPENSES = 'FETCHED_EXPENSES';
export const INPUT_CHANGE = 'INPUT_CHANGE';
